
lfg = function(j,k,l,n) {
  # generate the seed
  seed <- runif(j,0,2^l)
  for (i in 1:n) {
    seed[j+i] <- seed[i] + seed[j+i-k] %% 2^l
  }
  # standardize to [0:1]
  X = seed[(j+1):length(seed)]/max(seed)
  print(X)
}
# generate 4 new random numbers
plot(lfg(17,5,31,100), main="100 Numbers Generated by LFG(17,5,31)",
     xlab="Number of Observations", ylab="Generated Number", pch=19)

